name: api_event
description: Easy api-event
version: 1.3.0
homepage: https://github.com/MaximMonakhov/api_event

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.24.1
  connectivity_plus: ^1.0.6

flutter: